### ISSUE TITLE
Main and master branches both exist at the same time

### ISSUE THREAD

**Issue by WerySkok** [JCIBravo/MTR-Viewer#1]
![изображение](https://github.com/JCIBravo/MTR-Viewer/assets/15957616/ad2f85de-a590-4eee-b5ac-12d88383f2fc)
You may solve this problem by making `master` branch the default one and deleting `main` one. (or rename `master` to `main` and then force-push).

**Comment by JCIBravo** [comment]
Done! Thank you ^^
